version: '3.8'

services:
  orderly-bite:
    build: .
    ports:
      - "${HOST_PORT:-3000}:${CONTAINER_PORT:-5000}"
    environment:
      - PORT=${CONTAINER_PORT:-5000}
      - NODE_ENV=production
      # Add any other environment variables here
      # - OPENAI_API_KEY=${OPENAI_API_KEY}
      # - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      # - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
    restart: unless-stopped